export const KEYWORD_LIBRARY = {
  Protocols: [
    "report",
    "notify",
    "escalate",
    "incident notification",
    "incident coordination",
    "ICC",
    "governance",
    "alignment",
    "response plan",
    "approvals",
  ],
  Data: [
    "surveillance",
    "sampling",
    "inspection",
    "monitoring",
    "trace mapping",
    "tracing",
    "pathways",
    "verification",
    "residual risk",
    "spread picture",
  ],
  Stakeholders: [
    "stakeholders",
    "industry engagement",
    "guidance",
    "confidence",
    "trust",
    "operators",
    "boaters",
    "contractors",
    "regular updates",
  ],
  Constraints: [
    "containment",
    "movement controls",
    "quarantine",
    "restrictions",
    "enforcement",
    "decontamination",
    "disposal",
    "logistics",
    "high-risk",
  ],
  Communication: [
    "communication",
    "updates",
    "expectations",
    "briefings",
    "realistic updates",
    "follow-up",
    "clear messaging",
    "confidence",
  ],
  Expectations: [
    "close-out",
    "transition",
    "recovery",
    "final priorities",
    "verification",
    "discipline",
  ],
} as const;